### PR TITLE
Add lageanes dialects

### PR DESCRIPTION
**Pull request by mauscoelho**
## Description

This PR adds the dialects that come from the city of Lages and Amures region

### CODE REVIEW

**Comment by mauscoelho** [comment]
So, that's a really good topic 😂 There are some types of dialects in Santa Catarina and they are really different. One of them is the `catarina` and is common on the coast of Santa Catarina, but it is only a small part of the state.

As you can see on the image below, the `lageanes` represents the red part on the map:

screenshot 2019-02-26 at 10 34 43

But, is up to you to. If you prefer I merge it as a general dialect of the state of Santa Catarina

**Comment by hugoestevam** [comment]
Hi @mvfsillva, it's a great project, congrats!
In short, instead of dividing the state of Santa Catarina in two parts, people should bear in mind that although Santa Catarina is one of the smallest Brazilian states, it is the most culturally diverse. I wasn’t aware about the cultural shocks I would get by just crossing those different regions. It is crazy, but it is real. 
I want to demonstrate by a qualitative dialectical map below.

mapa-dialetal-v5

I think the better approach is they cannot be considered state dialects, once there usually is more than one dialect per state. (Only a suggest)

**Comment by mvfsillva** [comment]
## Guys this is amazing!

That is the idea of this project, the Brazilian cultural wealth is incredible, I did not imagine these divisions, let's improve!

Let's add a new node in this `json`, to facilitate the identify the state, what do you think @mauscoelho?

**Comment by mauscoelho** [comment]
Yes, for sure! 
Do you expect something like that?
```
{
    "dialect": "Aleijada",
    "meanings": ["Mulher de bons atributos físicos"],
    "examples": ["Uh, Aleijada!"],
    "state": "Santa Catarina"
}
```

**Comment by RodolfoSilva** [comment]
Hey @mauscoelho,

Thanks  for contributing!!

I think you can use this format:

```
{
  ...
  “commonIn”: [“Lages”]
}
```

I believe this is the better way to limit a dialect by zone.

**Comment by mauscoelho** [comment]
@RodolfoSilva Lages is the city if we follow this pattern I should add 23 cities on the node 🤔 according to [wikipedia](https://pt.wikipedia.org/wiki/Regi%C3%A3o_Metropolitana_de_Lages).

I think the better way is to group by state :) what do you think @mvfsillva ?

**Comment by hugoestevam** [comment]
Hi guys

I think this PR should propose a major change in the file structure of dialects because we understand that the dialect can cross the state boundaries.

For example, "Gringonês" can be seen in Xanxerê (SC) as well as in Erechim (RS), as well as "Lageanês" can be seen in Lages (SC) and in Vacaria (RS).

Therefore, I recommend the following structure:
**lageanes.json**
```
{
	name: "Lageanês",
	description: "Dialeto utilizado na região Serra de Santa Catarina e Rio Grande do Sul",
	crossingStates: ["SC", "RS"]
	dialects: [
	  {
		"dialect": "Aleijada",
		"meanings": ["Mulher de bons atributos físicos"],
		"examples": ["Uh, Aleijada!"]
	  },
	  {
		"dialect": "É só lavá",
		"meanings": ["O mesmo que, ninguém merece"],
		"examples": ["Olha o que ele fez, é só lavá!"]
	  }
	  ...
	]
}
```

I know, this has a big impact.  😬

**Comment by mvfsillva** [comment]
@hugoestevam 

> Hi guys
> 
> I think this PR should propose a major change in the file structure of dialects because we understand that the dialect can cross the state boundaries.
> 
> For example, "Gringonês" can be seen in Xanxerê (SC) as well as in Erechim (RS), as well as "Lageanês" can be seen in Lages (SC) and in Vacaria (RS).
> 
> Therefore, I recommend the following structure:
> **lageanes.json**
> 
> ```
> {
> 	name: "Lageanês",
> 	description: "Dialeto utilizado na região Serra de Santa Catarina e Rio Grande do Sul",
> 	crossingStates: ["SC", "RS"]
> 	dialects: [
> 	  {
> 		"dialect": "Aleijada",
> 		"meanings": ["Mulher de bons atributos físicos"],
> 		"examples": ["Uh, Aleijada!"]
> 	  },
> 	  {
> 		"dialect": "É só lavá",
> 		"meanings": ["O mesmo que, ninguém merece"],
> 		"examples": ["Olha o que ele fez, é só lavá!"]
> 	  }
> 	  ...
> 	]
> }
> ```
> I know, this has a big impact. 😬

Could you open an issue so we can discuss it?

**Comment by mvfsillva** [comment]
> @RodolfoSilva Lages is the city if we follow this pattern I should add 23 cities on the node 🤔 according to [wikipedia](https://pt.wikipedia.org/wiki/Regi%C3%A3o_Metropolitana_de_Lages).
> 
> I think the better way is to group by state :) what do you think @mvfsillva ?

Initially, I think it is best to group by states

**Comment by mvfsillva** [comment]
@mauscoelho 

I'm going to merge your pr and open an issue so we can think together about a better solution!

What do you think?

**Pull request merged**
